/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cbn_cn_ndkexample_MainActivity */

#ifndef _Included_cbn_cn_ndkexample_MainActivity
#define _Included_cbn_cn_ndkexample_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cbn_cn_ndkexample_MainActivity
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cbn_cn_ndkexample_MainActivity_getStringFromNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
